force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <label>Meetup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/RegistrationCode__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCode__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Registration Code</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/RegistrationLimit__c.field-meta.xml
<CustomField>
    <fullName>RegistrationLimit__c</fullName>
    <label>Registration Limit</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;Open&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/MeetupRegistration__c.object-meta.xml
<CustomObject>
    <label>Meetup Registration</label>
    <nameField>
        <label>Registration Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetup Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MeetupRegistration__c/fields/Meetup__c.field-meta.xml
<CustomField>
    <fullName>Meetup__c</fullName>
    <label>Meetup</label>
    <referenceTo>Meetup__c</referenceTo>
    <relationshipName>MeetupRegistrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MeetupRegistrationController.cls
public with sharing class MeetupRegistrationController {
    
    @AuraEnabled
    public static Meetup__c getMeetupByCode(String registrationCode) {
        Meetup__c meetup;

        try {
            meetup = [SELECT Id, Name, Status__c, RegistrationLimit__c FROM Meetup__c WHERE RegistrationCode__c =: registrationCode];
        } catch (Exception e) {
            AuraHandledException auraException = new AuraHandledException('No meetup with registration code: ' + registrationCode);
            auraException.setMessage('No meetup with registration code: ' + registrationCode);
            throw auraException;
        }
            
        if (meetup.Status__c == 'Closed') {
            AuraHandledException auraException = new AuraHandledException('The selected meetup has a status of \'Closed\'');
            auraException.setMessage('The selected meetup has a status of \'Closed\'');
            throw auraException;
        }

        if (!validateSpace(meetup)) {
            AuraHandledException auraException = new AuraHandledException('The selected meetup has no space remaining');
            auraException.setMessage('The selected meetup has no space remaining');
            throw auraException;            
        }

        return meetup;
    }

    @AuraEnabled
    public static List<MeetupRegistration__c> getMeetupRegistrationEmails(String meetupId) {
        List<MeetupRegistration__c> registrations = [SELECT Email__c FROM MeetupRegistration__c WHERE Meetup__c =: meetupId];

        return registrations;
    }

    @TestVisible
    private static Boolean validateSpace(Meetup__c meetup) {
        Integer count = [SELECT COUNT() FROM MeetupRegistration__c WHERE Meetup__c =: meetup.Id];

        return meetup.RegistrationLimit__c > count;
    }
}