force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <label>Meetup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/RegistrationCode__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCode__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Registration Code</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/RegistrationLimit__c.field-meta.xml
<CustomField>
    <fullName>RegistrationLimit__c</fullName>
    <label>Registration Limit</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;Open&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/testMeetupRegistrationController.cls
@isTest(SeeAllData=false)
public class testMeetupRegistrationController {
    @TestSetup
    static void init() {
        Meetup__c openMeetup = new Meetup__c (
            Name = 'Nuggets Game 1',
            Status__c = 'Open',
            RegistrationLimit__c = 1
        );

        Meetup__c closedMeetup = new Meetup__c (
            Name = 'Nuggets Game 2',
            Status__c = 'Closed',
            RegistrationLimit__c = 1
        );

        Meetup__c fullMeetup = new Meetup__c (
            Name = 'Nuggets Game 3',
            Status__c = 'Open',
            RegistrationLimit__c = 0
        );

        insert openMeetup; 
        insert closedMeetup;
        insert fullMeetup;
    }

    @isTest
    static void testGetMeetupByCode_NoMeetupFoundWithRegistraionCode_ThrowsException() {
        Test.startTest();
        
            try {
                Meetup__c meetup = MeetupRegistrationController.getMeetupByCode('');
            } catch (Exception ex) {
                System.assertEquals('No meetup with registration code: ', ex.getMessage());
            }

        Test.stopTest();
    }

    @isTest
    static void testGetMeetupByCode_SelectedMeetupIsClosed_ThrowsException() {
        Test.startTest();
        
            try {
                Meetup__c closedMeetup = [SELECT RegistrationCode__c FROM Meetup__c WHERE Name = 'Nuggets Game 2'];
                Meetup__c meetup = MeetupRegistrationController.getMeetupByCode(closedMeetup.RegistrationCode__c);
            } catch (Exception ex) {
                System.assertEquals('The selected meetup has a status of \'Closed\'', ex.getMessage());
            }

        Test.stopTest();
    }

    @isTest
    static void testGetMeetupByCode_SelectedMeetupIsFull_ThrowsException() {
        Test.startTest();
        
            try {
                Meetup__c fullMeetup = [SELECT RegistrationCode__c FROM Meetup__c WHERE Name = 'Nuggets Game 3'];
                Meetup__c meetup = MeetupRegistrationController.getMeetupByCode(fullMeetup.RegistrationCode__c);
            } catch (Exception ex) {
                System.assertEquals('The selected meetup has no space remaining' , ex.getMessage());
            }

        Test.stopTest();
    }

    @isTest
    static void testGetMeetupByCode_SelectedMeetupIsAvailabled_ReturnsMeeetup() {
        Test.startTest();

            Meetup__c openMeetup = [SELECT Id, RegistrationCode__c FROM Meetup__c WHERE Name = 'Nuggets Game 1'];
            Meetup__c actualMeetup = MeetupRegistrationController.getMeetupByCode(openMeetup.RegistrationCode__c);

            System.assertEquals(openMeetup.Id, actualMeetup.Id);

        Test.stopTest();
    }
}